version: "3.9"
services:
  api:
    build: 
      context: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8000:8000
  server:
    build:
      context: ./server
    ports:
      - "10101:445"
    environment:
      - H2O_WAVE_PORT=:445
  app:
    build:
      context: ./app
    environment:
      - H2O_WAVE_APP_ADDRESS=http://app:8000
      - H2O_WAVE_ADDRESS=http://server:445
    stdin_open: true
    depends_on: 
      - api
      - client
